/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthVmImport } from './routes/_auth/vm'
import { Route as AuthRequestsImport } from './routes/_auth/requests'
import { Route as AuthDashboardImport } from './routes/_auth/dashboard'
import { Route as AuthAdminImport } from './routes/_auth/admin'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthVmRoute = AuthVmImport.update({
  path: '/vm',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRequestsRoute = AuthRequestsImport.update({
  path: '/requests',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminRoute = AuthAdminImport.update({
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/admin': {
      preLoaderRoute: typeof AuthAdminImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard': {
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/requests': {
      preLoaderRoute: typeof AuthRequestsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/vm': {
      preLoaderRoute: typeof AuthVmImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthAdminRoute,
    AuthDashboardRoute,
    AuthRequestsRoute,
    AuthVmRoute,
  ]),
])

/* prettier-ignore-end */
